name: Release Workflow

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release body
        id: create_release_body
        run: |
          echo "Release notes for version ${{ github.ref_name }}"
          RELEASEVERSION=[${{ github.ref_name }}]
          echo "## Version $VERSION"
          RELEASEBODY=$(awk '/^## / { if (p) { exit }; if ($2 == "[0.3.1]") { p=1; next } } p && NF' CHANGELOG.md)
          echo "release body: $RELEASEBODY"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: release_${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
