name: Release Workflow

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release body
        id: create_release_body
        run: |
          echo "Release notes for version ${{ github.ref_name }}"
          RELEASEVERSION="[${{ github.ref_name }}]"
          echo "Version: $RELEASEVERSION"
          RELEASEBODY=$(awk -v ver="$RELEASEVERSION" '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next } } p && NF' CHANGELOG.md)
          {
            echo 'RELEASEBODY<<EOF'
            echo "${RELEASEBODY}"
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating release for version ${{ github.ref_name }}"
          echo "${{ steps.create_release_body.outputs.RELEASEBODY }}"
          gh release create "${{ github.ref_name }}" --title "release_${{ github.ref_name }}" --notes "${{ steps.create_release_body.outputs.RELEASEBODY }}"
          echo "Release created successfully"
